[
    "AIRDROP",
    "AIRLIFTING",
    "BOX",
    "BUNGEE CORD",
    "CARDBOARD BOX",
    "CARGO",
    "CONTAINER",
    "CONVOY",
    "CRATE",
    "DISTRIBUTE",
    "DROP ZONE",
    "DROPSHIP",
    "FORKLIFT",
    "FREIGHT",
    "HARNESS",
    "HAUL",
    "HELICOPTER",
    "HOIST",
    "HOOK",
    "INVENTORY",
    "LANDING ZONE",
    "LASHING",
    "LIFT",
    "LOAD",
    "LOADMASTER",
    "LOGISTICS",
    "MANIFEST",
    "NET",
    "OFFLOAD",
    "OFFLOAD ZONE",
    "PALLET",
    "PARACHUTE",
    "PAYLOAD",
    "RESUPPLY",
    "RIGGER",
    "RIGGING",
    "SECURE",
    "SECURING",
    "SHRINK WRAP",
    "SLING",
    "SLING LOAD",
    "STACK",
    "STACKING",
    "STRAP",
    "SUPPLY",
    "TRANSPORT",
    "UNLOAD",
    "VEHICLE",
    "WEBBING",
    "WINCH"
]
