[
    "ABRASION",
    "ACE MEDICAL",
    "ADDICTION",
    "ADENOSINE",
    "ALLERGIC",
    "AMMONIA",
    "AROMATHERAPY",
    "AUTOPSY",
    "AVULSION",
    "BACKBONE",
    "BANDAGE",
    "BLOOD",
    "CONTUSION",
    "COUGHING",
    "CRUSH",
    "CUT",
    "DOCTOR",
    "DOCTORS",
    "DOSAGE",
    "EPINEPHRINE",
    "FLATLINING",
    "HEALTH",
    "HEART",
    "HEART RATE",
    "LACERATION",
    "MEDICINE",
    "MORPHINE",
    "NURSE",
    "OVERDOSE",
    "PAIN",
    "PAIN KILLERS",
    "PATIENT",
    "PHARMACY",
    "PUNCTURE WOUND",
    "SPLINT",
    "UNCONSCIOUS",
    "VELOCITY WOUND",
    "VIRUS",
    "VISCOSITY",
    "WOUND",
    "BONESETTER"
]
