#define MAINPREFIX z
#define PREFIX qte_ace

#include "script_version.hpp"

#define VERSION         MAJOR.MINOR
#define VERSION_STR     MAJOR.MINOR.PATCHLVL.BUILD
#define VERSION_AR      MAJOR,MINOR,PATCHLVL,BUILD
#define VERSION_PLUGIN  MAJOR.MINOR.PATCHLVL.BUILD

#define REQUIRED_VERSION 2.20

#ifdef COMPONENT_BEAUTIFIED
    #define COMPONENT_NAME QUOTE(QTE ACE - COMPONENT_BEAUTIFIED)
#else
    #define COMPONENT_NAME QUOTE(QTE ACE - COMPONENT)
#endif
