[
    "BULLET",
    "CARTRIDGE",
    "CLIP",
    "DRUM MAGAZINE",
    "FEED LIP",
    "HELICAL MAGAZINE",
    "MAGAZINE",
    "OOPS THEY ALL SPILLED OUT AGAIN",
    "PINCHING FINGER",
    "POWDER",
    "QUICK LOADER",
    "SLIPPING",
    "SPRING",
    "STRIPPER CLIP"
]
