[
    "BACK PRESSURE",
    "BARREL",
    "BARREL SWAP",
    "BLAME PATTY",
    "BLOWBACK",
    "BRASS",
    "BREECH",
    "BUFFER",
    "BURNOUT",
    "CARBON BUILDUP",
    "CARTRIDGE",
    "CHAMBER",
    "CLEARING",
    "COOL DOWN",
    "COOLANT",
    "COOK OFF",
    "CYCLING",
    "DEGRADATION",
    "DISCHARGE",
    "DOUBLE FEED",
    "DRUM",
    "DUD",
    "EJECTION",
    "EXTRACT",
    "EXTRACTOR",
    "FAILURE TO EJECT",
    "FAILURE TO FEED",
    "FAILURE TO FIRE",
    "FATIGUE",
    "FEED RAMP",
    "FIRING PIN",
    "FRICTION",
    "FTE",
    "GAS IMPINGEMENT",
    "GAS OPERATED",
    "GAS TUBE",
    "GLOWING",
    "HANG FIRE",
    "HEADSPACE",
    "HEAT SHIELD",
    "HOT GAS",
    "JAM",
    "JAMMED CASE",
    "LAND AND GROOVE",
    "LOCKED BACK",
    "LODGED",
    "LUBE",
    "LUBRICATION",
    "MALFUNCTION",
    "MECHANICAL",
    "MELTING",
    "MISFIRE",
    "OVERHEATED",
    "PHOSPHATE",
    "PISTON",
    "PRIMER",
    "PROPELLANT",
    "RAPID FIRE",
    "RECOIL",
    "REMEDIAL",
    "RESIDUE",
    "RIFLING",
    "ROTATING BOLT",
    "SHELL",
    "SLAMFIRE",
    "SLOW ROUND",
    "SMOKING BARREL",
    "SOOTY",
    "SPENT CASE",
    "SPRING",
    "SQUIB",
    "STOVEPIPE",
    "STUCK",
    "SUPPRESSOR",
    "TAP RACK BANG",
    "THERMAL",
    "TRIGGER PULL",
    "WEAR"
]
